name: FastBuild
main: at.niemeczek.dev.fastbuild.FastBuild
version: 0.0.1
author: Harald Niemeczek
commands:
  build:
    description: This builds a roof.
    usage: " ====================================================\n
    §cFastBuild Help Menu \n
    §6/build help \n
    §r     Displays this help menu \n
    §6/build roof <Material> <height> \n
    §r     Builds a roof with <height> layers out of <Material>.\n
    §6/build roof_make_hollow\n
    §6/build rmh §r(Alias)\n
    §r     Hollows out roof. Make sure neighbour roofs are not the \n
    §r     same material!\n
    §6/build listbuilds [player]\n
    §r     Lists all stored builds \n
    §6/build undo [number]\n
    §6/build undo <number> [player]\n
    §r     undoes your last issued or by [number] specified build, \n
    §r     if player is specified, player's action will be undone. \n
    §6/build clearhistory \n
    §r     clears your history \n
    ====================================================
    "


    /build undo [number] [player]
         * if number is not set, last one is chosen
         * if player is not set, CommandSender is chosen




    permission: FastBuild.build.roof
    permission-message: You don't have permission for that command. You need permission FastBuild.build!
permissions:
    FastBuild.*:
        description: Permits all FastBuild commands and actions
        children:
            FastBuild.build.roof: true
            FastBuild.build.roof_make_hollow: true
    FastBuild.build.*:
        description: Permits all FastBuild commands
        children:
            FastBuild.build.roof: true
            FastBuild.build.roof_make_hollow: true
    FastBuild.build.roof:
        description: Allows /build roof
        default: op
    FastBuild.build.roof_make_hollow:
        description: Allows /build roof_make_hollow
        default: op
    FastBuild.build.listbuilds.self:
        description: Allows /build listbuilds
        default: op
    FastBuild.build.listbuilds.other:
        description: Allows /build listbuilds <player>
        default: op
    FastBuild.build.undo.self:
        description: Allows /build undo
        default: op
    FastBuild.build.undo.other:
        description: Allows /build undo <player>
        default: op